# BMC Platform modules

BMC_PLATFORM_MODULE_VERSION = 1.0

export BMC_PLATFORM_MODULE_VERSION

BMC_PLATFORM_MODULE = sonic-platform-bmc_$(BMC_PLATFORM_MODULE_VERSION)_amd64.deb
$(BMC_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bmc
$(BMC_PLATFORM_MODULE)_DEPENDS =
$(BMC_PLATFORM_MODULE)_PLATFORM = x86_64-kvm_x86_64-r1
SONIC_DPKG_DEBS += $(BMC_PLATFORM_MODULE)
