include $(PLATFORM_PATH)/sonic-version.mk
include $(PLATFORM_PATH)/platform-modules-bmc.mk
include $(PLATFORM_PATH)/one-image.mk
include $(PLATFORM_PATH)/onie.mk
include $(PLATFORM_PATH)/kvm-image.mk
include $(PLATFORM_PATH)/raw-image.mk
SONIC_DOCKER_IMAGES := $(filter-out $(DOCKER_LLDP) $(DOCKER_SNMP) $(DOCKER_FPM_FRR) $(DOCKER_ORCHAGENT) $(DOCKER_PLATFORM_MONITOR) $(DOCKER_DASH_ENGINE) $(DOCKER_AUDITD) $(DOCKER_AUDITD_WATCHDOG) $(DOCKER_BMP_WATCHDOG) $(DOCKER_SYSMGR) ,$(SONIC_DOCKER_IMAGES))

SONIC_INSTALL_DOCKER_IMAGES := $(filter-out $(DOCKER_LLDP) $(DOCKER_SNMP) $(DOCKER_FPM_FRR) $(DOCKER_ORCHAGENT) $(DOCKER_PLATFORM_MONITOR) $(DOCKER_DASH_ENGINE) $(DOCKER_AUDITD) $(DOCKER_AUDITD_WATCHDOG) $(DOCKER_BMP_WATCHDOG) $(DOCKER_SYSMGR) ,$(SONIC_INSTALL_DOCKER_IMAGES))

SONIC_ALL += $(SONIC_KVM_IMAGE)
