# Docker image for bmc

DOCKER_BMC_STEM = docker-bmc
DOCKER_BMC = $(DOCKER_BMC_STEM).gz
DOCKER_BMC_DBG = $(DOCKER_BMC_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_BMC)_PATH = $(DOCKERS_PATH)/$(DOCKER_BMC_STEM)

$(DOCKER_BMC)_DEPENDS += $(SONIC_BMCD)
$(DOCKER_BMC)_INSTALL_DEBS = $(SONIC_BMCD)

$(DOCKER_BMC)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_BMC)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_BMC)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_BMC)_VERSION = 1.0.0
$(DOCKER_BMC)_PACKAGE_NAME = bmc
# $(DOCKER_BMC)_WARM_SHUTDOWN_BEFORE = swss
# $(DOCKER_BMC)_FAST_SHUTDOWN_BEFORE = swss

$(DOCKER_BMC)_CONTAINER_NAME = bmc
$(DOCKER_BMC)_RUN_OPT += -t
$(DOCKER_BMC)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_BMC)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro
$(DOCKER_BMC)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
