# sonic-bmp package
# SONIC_BMCD = sonic-bmc_0.1_$(CONFIGURED_ARCH).deb
# $(SONIC_BMCD)_SRC_PATH = $(SRC_PATH)/sonic-bmc
# $(SONIC_BMCD)_DEPENDS  =  $(LIBSWSSCOMMON_DEV) $(LIBSWSSCOMMON)
# $(SONIC_BMCD)_RDEPENDS = $(LIBSWSSCOMMON)
# SONIC_DPKG_DEBS += $(SONIC_BMCD)

# sonic-bmc package

SONIC_BMC_VERSION = 1.0

export SONIC_BMC_VERSION

SONIC_BMCD = sonic-bmc_$(SONIC_BMC_VERSION)_$(CONFIGURED_ARCH).deb

$(SONIC_BMCD)_SRC_PATH = $(SRC_PATH)/sonic-bmc
# $(SONIC_BMCD)_DEB_BUILD_OPTIONS = nocheck
# $(SONIC_BMCD)_RDEPENDS =
# $(SONIC_BMCD)_DEPENDS =

SONIC_DPKG_DEBS += $(SONIC_BMCD)